# Generated by Django 2.1.3 on 2018-11-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sitioweb', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='editorialMedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('paginas', models.CharField(max_length=100)),
                ('fragmento', models.TextField(max_length=200)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.Editorial')),
            ],
        ),
    ]
