# Generated by Django 2.1.3 on 2018-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0003_auto_20181116_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
