# Generated by Django 2.1.3 on 2018-11-16 22:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0004_auto_20181116_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Acción y aventuras', 'Acción y aventuras'), ('Ciencia', 'Ciencia'), ('Ficción', 'Ficción'), ('Cómics', 'Cómics'), ('Cuentos', 'Cuentos'), ('relatosErótica', 'relatosErótica'), ('Fantástica', 'Fantástica'), ('Humor', 'Humor'), ('Infantil', 'Infantil'), ('Misterio', 'Misterio'), ('Narrativa', 'Narrativa'), ('Terror', 'Terror')], default=1, max_length=116),
            preserve_default=False,
        ),
    ]
