# Generated by Django 2.1.3 on 2018-11-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0005_libro_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
    ]
