# Generated by Django 2.1.3 on 2018-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0007_auto_20181116_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('Acción y aventuras', 'Acción y aventuras'), ('Ciencia', 'Ciencia'), ('Ficción', 'Ficción'), ('Cómics', 'Cómics'), ('Cuentos', 'Cuentos'), ('Erótica', 'Erótica'), ('Fantástica', 'Fantástica'), ('Humor', 'Humor'), ('Infantil', 'Infantil'), ('Misterio', 'Misterio'), ('Narrativa', 'Narrativa'), ('Terror', 'Terror')], max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fragmento',
            field=models.TextField(max_length=1000),
        ),
    ]
