# Generated by Django 2.1.3 on 2018-11-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0009_auto_20181116_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='libros',
        ),
        migrations.AddField(
            model_name='editorial',
            name='libros',
            field=models.ManyToManyField(to='Biblioteca.Libro'),
        ),
    ]
